[package]
name = "upgraded-pancake-server"
version = "0.1.0"
authors = ["Victor M. Suarez <svmnotn@gmail.com>"]

[dependencies]
rocket = "0.3.15"
rocket_codegen = "0.3.15"
serde_json = "1.0.24"
serde = "1.0.70"
serde_derive = "1.0.70"
rand = "0.5.4"
